site_name: Release Dashboard Docs
site_description: Documentation for Release Dashboard

nav:
  - Home: index.md

docs_dir: input/docs
site_dir: site

repo_url: https://github.com/Sriman-COGNIWIDE/BE-Release-Dash
edit_uri: edit/main/input/docs/

theme:
  name: mkdocs
