apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Release-Dashboard
  description: |
    A release dashboard to see the images running in the clusters
  links:
    - title: GitHub Repository
      url: https://github.com/Sriman-COGNIWIDE/BE-Release-Dash
    - title: Live Dashboard
      url: http://localhost:3001
  annotations:
    github.com/project-slug: Sriman-COGNIWIDE/BE-Release-Dash
    backstage.io/techdocs-ref: dir:docs
    jenkins.io/job-full-name: BE_Release_Dashboard
    backstage.io/jenkins-github-folder: BE_Release_Dashboard
    jenkins.io/github-folder: BE_Release_Dashboard
spec:
  type: service
  owner: rd-team
  lifecycle: production
  system: PairPoint
