apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: RD-api
  description: Retrieve environment details
spec:
  type: openapi
  lifecycle: production
  owner: rd-team
  system: PairPoint
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Environment API
      license:
        name: COGNIWIDE
    servers:
      - url: http://af634da2798dd4cf7bdeb15206358551-5125373207dfaf13.elb.eu-west-2.amazonaws.com
    paths:
      /api/all-envs:
        get:
          summary: List all environments
          responses:
            200:
              description: Success
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      environments:
                        type: array
                        items:
                          type: string
