apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: RD-api
  description: Retrieve environment details
spec:
  type: openapi
  lifecycle: production
  owner: rd-team
  system: PairPoint
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Environment API
      license:
        name: COGNIWIDE
    servers:
      - url: http://127.0.0.1:5001/inventory
    paths:
      /all-envs:
        get:
          summary: List all environments
          operationId: getAllEnvironments
          responses:
            '200':
              description: Successful response
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      environments:
                        type: array
                        items:
                          type: string
                    required:
                      - environments
