apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: RD-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: rd-team
  system: PairPoint
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: COGNIWIDE
    servers:
      - url: http://af634da2798dd4cf7bdeb15206358551-5125373207dfaf13.elb.eu-west-2.amazonaws.com
    paths:
      /platform_loe:
        get:
          summary: List all images in platform_loe
    ...
