apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: TAG-3-PROJECT
  description: This is a test project created via API
  tags:
    - test
    - api
    - demo
  annotations:
    github.com/project-slug: https://github.com/Sriman-COGNIWIDE/BE-Release-Dash
spec:
  type: service
  lifecycle: production
  owner: group:default/team-a
  system: Engineering
